/home/gamie/Work/Programs/process_stockinfo.php 2GO >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ABA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ABG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ABS >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ABSP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ACE >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ACPB1 >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ACPB2 >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ACR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AEV >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AGF >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AGI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ALCO >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ALCPB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ALHI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ALI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ALT >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ANI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ANS >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php APC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php APL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php APO >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php APX >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ARA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AT >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ATI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ATN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php AUB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BCB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BCOR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BDO >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BEL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BHI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BKR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BLFI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BLOOM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BMM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BPI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BRN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php BSC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CAB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CAL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CAT >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CDC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CEB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CEI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CEU >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CHI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CHIB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CHP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CIC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CIP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CNPF >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php COAL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php COL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php COSCO >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CPG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CPM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CROWN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php CYBR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DAVIN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DD >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DDPR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DFNN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DIZ >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DMC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DMPL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DNL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php DWC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ECP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php EDC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php EEI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php EG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ELI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php EMP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php EVER >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php EW >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FDC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FEU >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FFI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FGEN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FGENF >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FGENG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FJP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FLI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FMETF >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FNI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FOOD >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FPH >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FPHPC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php FPI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GEO >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GERI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GLO >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GLOPP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GMA7 >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GMAP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GPH >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GTCAP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GTPPA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php GTPPB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php H2O >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php HI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php HLCM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php HOUSE >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php HVN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php I >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ICT >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php IDC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php IMI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php IMP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php IMPB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ION >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php IPM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php IPO >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php IRC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php IS >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ISM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php JAS >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php JFC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php JGS >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php JOH >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php KPH >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LAND >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LBC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LCB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LFM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LIHC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LMG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LPZ >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LRP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LRW >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php LTG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MAC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MARC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MAXS >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MBC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MBT >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MCP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MED >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MEG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MER >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MFC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MFIN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MHC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MJC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MPI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MRC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MRSGI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MVC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MWC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MWIDE >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php MWP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php NI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php NIKL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php NOW >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php NRCP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php OPM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php OPMB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ORE >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php OV >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PAL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PAX >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PBB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PCOR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PERC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PF >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PFP2 >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PGOLD >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PHA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PHEN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PHES >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PHN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PIP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PIZZA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PLC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PMPC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PNB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PNX >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php POPI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PPC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PRC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PRF2B >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PRIM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PRMX >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PSB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PSPC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PTC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PX >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php PXP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php RCB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php RCI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php RFM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php RLC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php RLT >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ROCK >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ROX >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php RRHI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php RWM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SBS >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SCC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SECB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SEVN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SFI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SFIP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SGI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SHLPH >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SHNG >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SLF >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SLI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC2B >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC2C >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC2D >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC2E >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC2F >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC2G >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC2H >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMC2I >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SMPH >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SPC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SPM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SSI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php STI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php STR >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php SUN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php T >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php TAPET >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php TECH >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php TEL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php TFC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php TFHI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php TUGS >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php UBP >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php UNI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php UPM >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php URC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php V >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php VITA >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php VLL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php VMC >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php VUL >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php VVT >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php WEB >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php WIN >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php WPI >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php X >> /home/gamie/Work/log/process_stockinfo.log
/home/gamie/Work/Programs/process_stockinfo.php ZHI >> /home/gamie/Work/log/process_stockinfo.log
