/Users/gamie/Work/pse/process_stockinfo.php 2GO >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ABA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ABG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ABS >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ABSP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ACE >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ACPB1 >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ACPB2 >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ACR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AEV >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AGF >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AGI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ALCO >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ALCPB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ALHI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ALI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ALT >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ANI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ANS >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php APC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php APL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php APO >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php APX >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ARA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AT >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ATI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ATN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php AUB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BCB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BCOR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BDO >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BEL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BHI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BKR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BLFI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BLOOM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BMM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BPI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BRN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php BSC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CAB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CAL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CAT >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CDC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CEB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CEI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CEU >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CHI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CHIB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CHP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CIC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CIP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CNPF >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php COAL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php COL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php COSCO >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CPG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CPM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CROWN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php CYBR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DAVIN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DD >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DDPR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DFNN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DIZ >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DMC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DMPL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DNL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php DWC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ECP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php EDC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php EEI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php EG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ELI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php EMP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php EVER >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php EW >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FDC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FEU >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FFI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FGEN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FGENF >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FGENG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FJP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FLI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FMETF >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FNI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FOOD >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FPH >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FPHPC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php FPI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GEO >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GERI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GLO >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GLOPP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GMA7 >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GMAP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GPH >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GTCAP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GTPPA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php GTPPB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php H2O >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php HI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php HLCM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php HOUSE >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php HVN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php I >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ICT >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php IDC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php IMI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php IMP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php IMPB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ION >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php IPM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php IPO >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php IRC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php IS >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ISM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php JAS >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php JFC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php JGS >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php JOH >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php KPH >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LAND >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LBC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LCB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LFM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LIHC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LMG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LPZ >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LRP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LRW >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php LTG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MAC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MARC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MAXS >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MBC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MBT >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MCP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MED >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MEG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MER >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MFC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MFIN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MHC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MJC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MPI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MRC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MRSGI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MVC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MWC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MWIDE >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php MWP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php NI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php NIKL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php NOW >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php NRCP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php OPM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php OPMB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ORE >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php OV >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PAL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PAX >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PBB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PCOR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PERC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PF >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PFP2 >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PGOLD >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PHA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PHEN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PHES >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PHN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PIP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PIZZA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PLC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PMPC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PNB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PNX >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php POPI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PPC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PRC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PRF2B >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PRIM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PRMX >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PSB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PSPC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PTC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PX >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php PXP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php RCB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php RCI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php RFM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php RLC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php RLT >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ROCK >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ROX >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php RRHI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php RWM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SBS >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SCC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SECB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SEVN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SFI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SFIP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SGI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SHLPH >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SHNG >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SLF >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SLI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC2B >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC2C >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC2D >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC2E >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC2F >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC2G >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC2H >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMC2I >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SMPH >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SPC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SPM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SSI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php STI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php STR >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php SUN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php T >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php TAPET >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php TECH >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php TEL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php TFC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php TFHI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php TUGS >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php UBP >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php UNI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php UPM >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php URC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php V >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php VITA >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php VLL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php VMC >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php VUL >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php VVT >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php WEB >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php WIN >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php WPI >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php X >> /Users/gamie/Work/log/process_stockinfo.log
/Users/gamie/Work/pse/process_stockinfo.php ZHI >> /Users/gamie/Work/log/process_stockinfo.log
